#cloud-config
# vim: syntax=yaml

packages:
- docker.io
- jq

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

write_files:

#- content: |
#    {
#        "HELLO":"world",
#        "GOODBYE:"world
#    }
#  path: /home/ubuntu/env.json

- encoding: b64
  content: ewogICAgIkhFTExPIjoid29ybGQiLAogICAgIkdPT0RCWUU6IndvcmxkCn0K
  path: /home/ubuntu/env.json

runcmd:
- cd '/home/ubuntu/'
- $( cat env.json | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"' )
- curl -L -o cloud-init.sh 'https://raw.githubusercontent.com/asw101/dev/main/scripts/cloud-init/cloud-init.sh'
- bash cloud-init.sh

